language: go
go: stable
script:
  - go run analysis.go ./...
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o "mkcert-$(git describe --tags)-linux-amd64"
    -ldflags "-X main.Version=$(git describe --tags)"
  - CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build -o "mkcert-$(git describe --tags)-linux-arm"
    -ldflags "-X main.Version=$(git describe --tags)"
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o "mkcert-$(git describe --tags)-darwin-amd64"
    -ldflags "-X main.Version=$(git describe --tags)"
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o "mkcert-$(git describe --tags)-windows-amd64.exe"
    -ldflags "-X main.Version=$(git describe --tags)"

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: mkcert-*
  api_key:
    secure: icb6XcBlklso6Ea1anG6BrppNt5YHXGeUZvRQogj9br83d4qJ6Vef5bnhJ/61iu/zJkcvHFmy0ZRoMjRpyJxh913IcmdWEO3PN0YynWAUnAyiDPjMyTRTtLqUmKYx1j2yRQM5C0ARKWuwPpjTXYTGMzvIBQyfeey/gxMX2G+YPxM1IGEQ212uBblUwplMWySo+Z8shBOXpYMlyWhIz32+QLSX1UZYR6GBmY9fZfECRM2af6p0jle9G8Qinx1PTFJR6htZGEChXdPhpDFSJ58y5DrlSguE8kKIg6u5e5potRYpP2VGD4Arj1F82RpdC0yUiurDhyESAXhpvjp0AuoDmJ5WkcDRgQAY1zPmevO17/LNcusdQagN01fWmcChIVvx5BNeOPYFx4osvRKsEzMDMAJb+stBT+yvkcewJqll0DmVEo6vgf/QJBwvGBn/3H7xXZonWDOlqPwugShuLIG6Vyq8C3SoKOogPh75HSu9fvBoBdOWB3/w1EVRfHrcbTg/w9O3INSHYsKyHfdPOEdBUnzo4XNEHSewcBcgTpht6m+ZJo+WbJwoBa6UuqJj4xfUTTt+72ZZ6DwB2H4Ry1ddgrEUCLEsL6F9cVkZ/ofXEIntlUDh74MKa/3tHo2aPT2mGKiN0HDeDRXS+P0E/3A8YUjbdsTFaPvYevKHPyTg3A=
  on:
    repo: fchastanet/mkcert
    tags: true

before_install:
  - openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
