language: go
go: stable
script:
  - go run analysis.go ./...
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o "mkcert-$(git describe --tags)-linux-amd64"
    -ldflags "-X main.Version=$(git describe --tags)"
  - CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build -o "mkcert-$(git describe --tags)-linux-arm"
    -ldflags "-X main.Version=$(git describe --tags)"
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o "mkcert-$(git describe --tags)-darwin-amd64"
    -ldflags "-X main.Version=$(git describe --tags)"
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o "mkcert-$(git describe --tags)-windows-amd64.exe"
    -ldflags "-X main.Version=$(git describe --tags)"

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: mkcert-*
  api_key:
    secure: "NQbcbsn6PAKBOK51vQOjuV7MAUEycJtuAna5+XaQn21Rh8k+d+OWxaeeKDn4SMsovNO8HUjilEyREibZhSfSZqD4eCaOP0iBL0y9yRpDQJ07ZRfvauCtsOA6giWWV7ek2nCFKJAUeXSvGxfmUlxFVUy/VuvHZh8Yp129OGyQB2+Kzu05kn2TxC/w6uey/DJiVvW6iIF/6xYtAQ3ONI4DzPB8bGbpjT7Mnqy56V+A+VK9ANnxSqIlZ9BpvXb0KJBwZnabSRsf1koi5G/12rjs+825pv+Ojs4g6o2LwQFELMx+eXd1CokrJAk3h7kDNYZW1aSnIYNU8fpn4JdaO2XbPTw3wbRRPGLi6KJJ/bRhRtlVW801Q2Y+CJiPY1i9PxiCG53tACjnw5RHFchlFlDel4MHsu7GyvxE5aNZFKk91PwvM87TRM2qoW7HM929eJPo3x9dQnnopvg0AVcgbAiGs9f5mNjwhoBU2sbV4LnzYq8tVQg2o+R6u90z/nVDTbXVcg3xoV3ui25LyQgfHjtVV4z84PdxMP+rRF4wClpXKkemWOmHOMkyPXXmffmGxaDCvKZReHjBSdUdTIl/brIkyX74P2JCMiHJZ1K8hHjD6QzfoM6zONl26UPO3FRCxGpINfcnFCXdVGHqU5Bc10VzNsV+g+ik87Y9r3ps6cgKe5E="
  on:
    repo: fchastanet/mkcert
    tags: true

before_install:
  - openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
